version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=/api
    networks:
      - autokube-network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - autokube-network

networks:
  autokube-network:
    driver: bridge